AppSaresp_2024/Models/Aluno.cs
using System.ComponentModel.DataAnnotations;

namespace AppSaresp_2024.Models
{
    public class Aluno
    {
        [Display(Name = "Código")]
        public int? idAluno { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]

        public string nome { get; set; }

        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "O campo E-mail é obrigatório.")]
        [EmailAddress(ErrorMessage = "E-mail inválido.")]
        public string email { get; set; }

        [Required(ErrorMessage = "O campo Série é obrigatório.")]
        [StringLength(1, ErrorMessage = "A Série deve ter 1 caractere.")]
        [RegularExpression("^[0-9]$", ErrorMessage = "A Série deve ser um número de 0 a 9.")]
        [Display(Name = "Série")]
        public string serie { get; set; }

        [Required(ErrorMessage = "O campo Turma é obrigatório.")]
        [Display(Name = "Turma")]
        public string turma { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo Telefone é obrigatório.")]
        [StringLength(11, ErrorMessage = "O Telefone deve ter no máximo 11 caracteres.")]
        [RegularExpression("^[0-9]{11}$", ErrorMessage = "O telefone deve conter apenas números e ter 11 dígitos.")]
        public string telefone { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.Date)]
        public DateTime dataNasc { get; set; }
    }
}

AppSaresp_2024/Models/ErrorViewModel.cs
namespace AppSaresp_2024.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppSaresp_2024/Models/ProfessorAplicador.cs
using System.ComponentModel.DataAnnotations;

namespace AppSaresp_2024.Models
{
    public class ProfessorAplicador
    {
        [Display(Name = "Código")]
        public int? idProfessor { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]

        public string nome { get; set; }

        [Display(Name = "CPF")]
        [Required(ErrorMessage = "O campo CPF é obrigatório.")]
        [StringLength(11, ErrorMessage = "O CPF deve ter exatamente 11 dígitos.")]
        [RegularExpression("^[0-9]{11}$", ErrorMessage = "O CPF deve conter apenas números e ter 11 dígitos.")]
        public string CPF { get; set; }

        [Display(Name = "RG")]
        [Required(ErrorMessage = "O campo RG é obrigatório.")]
        [StringLength(9, ErrorMessage = "O RG deve ter 9 caracteres.")]
        public string RG { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo Telefone é obrigatório.")]
        [StringLength(11, ErrorMessage = "O Telefone deve ter no máximo 11 caracteres.")]
        [RegularExpression("^[0-9]{11}$", ErrorMessage = "O telefone deve conter apenas números e ter 11 dígitos.")]
        public string telefone { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.Date)]
        public DateTime dataNasc { get; set; }
    }
}

AppSaresp_2024/Controllers/AlunoController.cs
using AppSaresp_2024.Models;
using AppSaresp_2024.Repository.Contract;
using Microsoft.AspNetCore.Mvc;
using MySqlX.XDevAPI;

namespace AppSaresp_2024.Controllers
{
    public class AlunoController : Controller
    {
        private IAlunoRepository _alunoRepository;
        public AlunoController(IAlunoRepository alunoRepository)
        {
            _alunoRepository = alunoRepository;
        }
        public IActionResult Index()
        {
            return View(_alunoRepository.ObterTodosAlunos());
        }
        [HttpGet]
        public IActionResult CadastrarAluno()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarAluno(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _alunoRepository.Cadastrar(aluno);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarAluno(int id)
        {
            return View(_alunoRepository.ObterAluno(id));
        }
        [HttpPost]
        public IActionResult AtualizarAluno(Aluno aluno)
        {
            _alunoRepository.Atualizar(aluno);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesAluno(int id)
        {
            return View(_alunoRepository.ObterAluno(id));
        }
        [HttpPost]
        public IActionResult DetalhesAluno(Aluno aluno)
        {
            _alunoRepository.Atualizar(aluno);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirAluno(int id)
        {
            _alunoRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppSaresp_2024/Controllers/HomeController.cs
using AppSaresp_2024.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppSaresp_2024.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppSaresp_2024/Controllers/ProfessorAplicadorController.cs
using AppSaresp_2024.Models;
using AppSaresp_2024.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppSaresp_2024.Controllers
{
    public class ProfessorAplicadorController : Controller
    {
        private IProfessorAplicadorRepository _professorAplicadorRepository;
        public ProfessorAplicadorController(IProfessorAplicadorRepository professorAplicadorRepository)
        {
            _professorAplicadorRepository = professorAplicadorRepository;
        }
        public IActionResult Index()
        {
            return View(_professorAplicadorRepository.ObterTodosProfessores());
        }
        [HttpGet]
        public IActionResult CadastrarProfessorAplicador()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarProfessorAplicador(ProfessorAplicador professorAplicador)
        {
            if (ModelState.IsValid)
            {
                _professorAplicadorRepository.Cadastrar(professorAplicador);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarProfessorAplicador(int id)
        {
            return View(_professorAplicadorRepository.ObterProfessor(id));
        }
        [HttpPost]
        public IActionResult AtualizarProfessorAplicador(ProfessorAplicador professorAplicador)
        {
            _professorAplicadorRepository.Atualizar(professorAplicador);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesProfessorAplicador(int id)
        {
            return View(_professorAplicadorRepository.ObterProfessor(id));
        }
        [HttpPost]
        public IActionResult DetalhesProfessorAplicador(ProfessorAplicador professorAplicador)
        {
            _professorAplicadorRepository.Atualizar(professorAplicador);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirProfessorAplicador(int id)
        {
            _professorAplicadorRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppSaresp_2024/Views/Aluno/AtualizarAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "AtualizarAluno";
}

<h4>Editar o Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarAluno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idAluno" class="form-control" />

            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="serie" class="control-label"></label>
                <input asp-for="serie" class="form-control" />
                <span asp-validation-for="serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="turma" class="control-label"></label>
                <input asp-for="turma" class="form-control" />
                <span asp-validation-for="turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataNasc" class="control-label"></label>
                <input type="date" asp-for="dataNasc" class="form-control" />
                <span asp-validation-for="dataNasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/Aluno/CadastrarAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "CadastrarAluno";
}

<h1>Cadastrar Aluno</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarAluno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="serie" class="control-label"></label>
                <input asp-for="serie" class="form-control" />
                <span asp-validation-for="serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="turma" class="control-label"></label>
                <input asp-for="turma" class="form-control" />
                <span asp-validation-for="turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataNasc" class="control-label"></label>
                <input asp-for="dataNasc" class="form-control" />
                <span asp-validation-for="dataNasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a class="btn btn-primary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/Aluno/DetalhesAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "DetalhesAluno";
}

<h1>Detalhes Aluno</h1>

<div>
    <h4>Alunos</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.idAluno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.idAluno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.serie)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.serie)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.turma)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.turma)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dataNasc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dataNasc)
        </dd>
    </dl>
</div>
<br />
<button type="button" class="btn btn-primary botaoeditar">
    @Html.ActionLink("Editar", "AtualizarAluno", new { id = Model.idAluno })
</button>
<button type="button" class="btn btn-primary botaoeditar">
    @Html.ActionLink("Voltar", "Index")
</button>
</div>

AppSaresp_2024/Views/Aluno/Index.cshtml
@model IEnumerable<AppSaresp_2024.Models.Aluno>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Alunos</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(model => model.idAluno) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.nome) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.email)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.serie)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.turma)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.telefone)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.dataNasc) </th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Aluno aluno in Model)
            {
                <tr>
                    <td>@aluno.idAluno)</td>
                    <td>@aluno.nome</td>
                    <td>@aluno.email</td>
                    <td>@aluno.serie º</td>
                    <td>@aluno.turma</td>
                    <td>@aluno.telefone</td>
                    <td>@aluno.dataNasc.ToString("dd/MM/yyyy")</td>
                    <td>
                        <button type="button" class="btn btn-warning botaoeditar">
                            @Html.ActionLink("Editar", "AtualizarAluno", new { id = aluno.idAluno })
                        </button>

                        <button type="button" class="btn btn-secondary botaodetalhes">
                            @Html.ActionLink("Detalhes", "DetalhesAluno", new { id = aluno.idAluno })
                        </button>

                        <button type="button" class="btn btn-danger botaoexcluir">
                            @Html.ActionLink("Excluir", "ExcluirAluno", new { id = aluno.idAluno },
                                     new { onclick = "return confirm('Deseja realmente desativar?');" })
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" asp-action="CadastrarAluno" asp-controller="Aluno">Cadastrar</a></p>

AppSaresp_2024/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppSaresp_2024/Views/ProfessorAplicador/AtualizarProfessorAplicador.cshtml
@model AppSaresp_2024.Models.ProfessorAplicador

@{
    ViewData["Title"] = "AtualizarProfessorAplicador";
}

<h4>Editar o Usuário</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProfessorAplicador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idProfessor" class="form-control" />

            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataNasc" class="control-label"></label>
                <input type="date" asp-for="dataNasc" class="form-control" />
                <span asp-validation-for="dataNasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/ProfessorAplicador/CadastrarProfessorAplicador.cshtml
@model AppSaresp_2024.Models.ProfessorAplicador

@{
    ViewData["Title"] = "CadastrarProfessorAplicador";
}

<h1>Cadastrar Professor Aplicador</h1>

<h4>Professor Aplicador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarProfessorAplicador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataNasc" class="control-label"></label>
                <input asp-for="dataNasc" class="form-control" />
                <span asp-validation-for="dataNasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a class="btn btn-primary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/ProfessorAplicador/DetalhesProfessorAplicador.cshtml
@model AppSaresp_2024.Models.ProfessorAplicador

@{
    ViewData["Title"] = "DetalhesProfessorAplicador";
}

<h1>Detalhes Professor Aplicador</h1>

<div>
    <h4>Professor Aplicador</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.idProfessor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.idProfessor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RG)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RG)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dataNasc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dataNasc)
        </dd>
    </dl>
</div>
<br />
<button type="button" class="btn btn-primary botaoeditar">
    @Html.ActionLink("Editar", "AtualizarProfessorAplicador", new { id = Model.idProfessor })
</button>
<button type="button" class="btn btn-primary botaoeditar">
    @Html.ActionLink("Voltar", "Index")
</button>
</div>

AppSaresp_2024/Views/ProfessorAplicador/Index.cshtml
@model IEnumerable<AppSaresp_2024.Models.ProfessorAplicador>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Professor Aplicador</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(model => model.idProfessor) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.nome) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.CPF)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.RG)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.telefone)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.dataNasc) </th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ProfessorAplicador professorAplicador in Model)
            {
                <tr>
                    <td>@professorAplicador.idProfessor)</td>
                    <td>@professorAplicador.nome</td>
                    <td>@professorAplicador.CPF</td>
                    <td>@professorAplicador.RG</td>
                    <td>@professorAplicador.telefone</td>
                    <td>@professorAplicador.dataNasc.ToString("dd/MM/yyyy")</td>
                    <td>
                        <button type="button" class="btn btn-warning botaoeditar">
                            @Html.ActionLink("Editar", "AtualizarProfessorAplicador", new { id = professorAplicador.idProfessor })
                        </button>

                        <button type="button" class="btn btn-secondary botaodetalhes">
                            @Html.ActionLink("Detalhes", "DetalhesProfessorAplicador", new { id = professorAplicador.idProfessor })
                        </button>

                        <button type="button" class="btn btn-danger botaoexcluir">
                            @Html.ActionLink("Excluir", "ExcluirProfessorAplicador", new { id = professorAplicador.idProfessor },
                                     new { onclick = "return confirm('Deseja realmente desativar?');" })
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" asp-action="CadastrarProfessorAplicador" asp-controller="ProfessorAplicador">Cadastrar</a></p>

AppSaresp_2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppSaresp_2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppSaresp_2024.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppSaresp_2024</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Cadastrar Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProfessorAplicador" asp-action="Index">Cadastrar Professor Aplicador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppSaresp_2024 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>